# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout do codigo do projeto
    - uses: actions/checkout@v2
     
    # Setup do Node.JS 
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }} 
    
    # instalando as dependencias
    - run: npm install
    
    # limpando ambiente de report
    - run: npm run clean:project

    # executar os testes 
    - run: npm run cy:run:spec
    
    # gerar o relatorio em html
    - run: npm run allure:generate
    - run: npm run allure:open


    - name: Allure report
      # You may pin to the exact commit or the version.
      # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
      uses: afiore/action-allure-report@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: allure-report
        FOLDER: allure-report
